[supervisord]
nodaemon=true
user=root

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true

[program:api-principal]
# Tu API recibiendo las peticiones web
command=uvicorn main:app --host 127.0.0.1 --port 5000
autostart=true
autorestart=true

[program:worker-procesamiento]
# Tu script secundario que se queda escuchando tareas en bucle
command=python worker.py
autostart=true
autorestart=true
# Si el script falla, Supervisord lo levanta automáticamente
startretries=3
