events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        # ==========================================
        # BLOQUE 1: FRONTEND (Archivos Estáticos / Angular / React)
        # -> Borra este bloque si tu app NO tiene interfaz gráfica.
        # ==========================================
        location / {
            root /var/www/html; # Ruta donde Docker copió tu frontend compilado
            index index.html;
            
            # El try_files es VITAL para que no salga error 404 al recargar en Angular
            try_files $uri $uri/ /index.html; 
        }

        # ==========================================
        # BLOQUE 2: BACKEND / API (Proxy Inverso)
        # -> Borra este bloque si solo vas a servir una web estática sin base de datos.
        # ==========================================
        # OJO: Si borraste el Bloque 1 y quieres que el backend reciba 
        # TODO el tráfico directamente, cambia "location /api/ {" por "location / {"
        location /api/ {
            
            # Cambia el puerto (ej. 5000 para Spring Boot/Flask, 8000 para FastAPI)
            proxy_pass http://127.0.0.1:5000; 
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
